DjangoProject/DjangoProject/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

urlpatterns = [
    url(r'^', include('SensorPoll.urls')),
	url(r'^SensorPoll/', include('SensorPoll.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

DjangoProject/SensorPoll/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^tables/$', views.tables, name='tables'),
    url(r'^charts/$', views.charts, name='charts'),
]

DjangoProject/SensorPoll/models.py
from django.db import models

class SensorPacket(models.Model):

    address = models.IntegerField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    data = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return ('address: ' + str(self.address) + ', Time: ' + str(self.time_stamp) + ', Data: '+ str(self.data))

class AveragedData(models.Model):

    address = models.IntegerField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    data = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return ('address: ' + str(self.address) + ',    Time: ' + str(self.time_stamp) + ',    Data: '+ str(self.data))

class HourlySensorData(models.Model):

    address = models.IntegerField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    data = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return ('address: ' + str(self.address) + ',    Time: ' + str(self.time_stamp) + ',    Data: '+ str(self.data))

class DailyAverageSensorData(models.Model):

    address = models.IntegerField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    data = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return ('address: ' + str(self.address) + ',    Time: ' + str(self.time_stamp) + ',    Data: '+ str(self.data))

class ActiveSensors(models.Model):
    Sensor_number = models.IntegerField()
    Sensor_name = models.CharField(max_length=100)

    def __str__(self):
        return self.Sensor_name

DjangoProject/SensorPoll/forms.py
from django import forms

from models import *

class ActiveSensorsForm(forms.ModelForm):
    class Meta:
        model = ActiveSensors
        fields = ('Sensor_number', 'Sensor_name')
           

DjangoProject/SensorPoll/views.py
from django.http import Http404
from django.shortcuts import render
from .models import SensorPacket
from .models import AveragedData, ActiveSensors, HourlySensorData
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from .forms import ActiveSensorsForm

def index(request):
    form = ActiveSensorsForm()
    packets = SensorPacket.objects.all()
    activeSensors = ActiveSensors.objects.all().order_by('Sensor_number')
    polledSensors = SensorPacket.objects.values('address').distinct().order_by('address')
    context = {'packets':packets, 'activeSensors':activeSensors, 'polledSensors':polledSensors,'form':form}

    if request.method == "POST":
        if request.POST['submit']=='removeSensor':
            try:
                sensorId = request.POST['Sensor_selected'].split(":")
                toDelete = ActiveSensors.objects.get(Sensor_number=sensorId[0])
                toDelete.delete()
            except:
                raise Http404("Could not delete sensor")

        elif request.POST['submit']=='addSensor':
            try:
                activeSensor = ActiveSensors.objects.get(Sensor_number=request.POST['Sensor_number'])
                activeSensor.Sensor_name=request.POST['Sensor_name']
                activeSensor.save()
            except:
                newSensor = ActiveSensorsForm(request.POST)
                if newSensor.is_valid():
                    newSensor.save()
    else:
        form = ActiveSensorsForm()

    return render(request, 'SensorPoll/index.html', context)

def tables(request):

    packets_list = SensorPacket.objects.all()
    paginator = Paginator(packets_list, 25)
    page = request.GET.get('page')
    try:
        packets = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        packets = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        packets = paginator.page(paginator.num_pages)

    context = {'packets':packets,}
    return render(request, 'SensorPoll/tables.html', context)

def charts(request):
    
    hourly_packs = HourlySensorData.objects.all()
    averaged_packs = AveragedData.objects.all()
    context = {'averaged_packs':averaged_packs,'hourly_packs':hourly_packs,}
    return render(request, 'SensorPoll/charts.html', context)

DjangoProject/SensorPoll/templates/SensorPoll/charts.html
{% extends "base.html" %}

{% block chartsButton %}
    class="active"
{% endblock %}

{% block pageHeader %}
    Charts
    <small>Subheading</small>
{% endblock %}

{% block breadcrumb %}
<li>
    <i class="fa fa-dashboard"></i>  <a href="{% url 'index' %}">Dashboard</a>
</li>
<li class="active">
    <i class="fa fa-bar-chart-o"></i> Charts
</li>
{% endblock %}
{% block row %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-green">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Quarter Hour Data</h3>
            </div>
            <div class="panel-body">
                <div id="Quarter Hour Data"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-green">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Hourly Data</h3>
            </div>
            <div class="panel-body">
                <div id="Hourly Data"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block chartsData %}
<script>
    $(function () {
        new Morris.Line({
            // ID of the element in which to draw the chart.
            element: 'Quarter Hour Data',
            // Chart data records -- each entry in this array corresponds to a point on
            // the chart.
            data: [
                //FIXME Make the address filter based on some table of ranges somewhere 
                {% for packet in averaged_packs %}
                    {% if packet.address < 11 %}
                        {time: '{{packet.time_stamp|date:"c"}}', '{{packet.address}}': {{packet.data}} },
                    {% endif %}
                {% endfor %}
                ],
            // The name of the data record attribute that contains x-values.
            xkey: 'time',
            // A list of names of data record attributes that contain y-values.
            ykeys: ['1', '2'],
            // Labels for the ykeys -- will be displayed when you hover over the
            // chart.
            labels: ['Sensor 1', 'Sensor 2'],
            postUnits: String.fromCharCode(176) + "C",
            dateFormat: function (x) { 
                var monthNames = [
                  "January", "February", "March",
                  "April", "May", "June", "July",
                  "August", "September", "October",
                  "November", "December"
                ];
                var date = new Date(x); 
                var hour = date.getHours();
                var minute = date.getMinutes();
                minute = ("0" + minute).slice(-2);
                var month = date.getMonth();
                var day = date.getDate();
                var year = date.getFullYear();
                return (hour +":"+minute + " " + monthNames[month] + " " + day +", " + year);
            },
            resize: true
        });
    });
</script>
<script>
    $(function () {
        new Morris.Line({
            // ID of the element in which to draw the chart.
            element: 'Hourly Data',
            // Chart data records -- each entry in this array corresponds to a point on
            // the chart.
            data: [
                {% for packet in hourly_packs %}
                    {time: '{{packet.time_stamp|date:"c"}}', '{{packet.address}}': {{packet.data}} },
                {% endfor %}
            ],
            // The name of the data record attribute that contains x-values.
            xkey: 'time',
            // A list of names of data record attributes that contain y-values.
            ykeys: ['1', '2'],
            // Labels for the ykeys -- will be displayed when you hover over the
            // chart.
            labels: ['Sensor 1', 'Sensor 2'],
            postUnits: String.fromCharCode(176) + "C",
            dateFormat: function (x) {
                var monthNames = [
                  "January", "February", "March",
                  "April", "May", "June", "July",
                  "August", "September", "October",
                  "November", "December"
                ];
                var date = new Date(x);
                var hour = date.getHours();
                var minute = date.getMinutes();
                minute = ("0" + minute).slice(-2);
                var month = date.getMonth();
                var day = date.getDate();
                var year = date.getFullYear();
                return (hour +":"+minute + " " + monthNames[month] + " " + day +", " + year);
            },
            resize: true
        });
    });
</script>
{% endblock %}

DjangoProject/SensorPoll/templates/SensorPoll/index.html
{% extends "base.html" %}

{% block dashboardButton %}
    class="active"
{% endblock %}

{% block pageHeader %}
    Dashboard
<small>Subheading</small>
{% endblock %}

{% block breadcrumb %}
<li class="active">
    <i class="fa fa-dashboard"></i>  <a href="{% url 'index' %}">Dashboard</a>
</li>
{% endblock %}

{% block row %}
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Active Sensors</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Sensor #</th>
                                    <th>Sensor Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for sensor in activeSensors %}
                                <tr>
                                    <td> {{sensor.Sensor_number}}</td>
                                    <td> {{sensor.Sensor_name}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Add Sensor</h3>
            </div>
                <div class="panel-body">
                    <div class="row">
                        <form role="form" method="POST">
                            {% csrf_token %}
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Sensor #</label>
                                    <select class="form-control" id="id_Sensor_number" type="number" name="Sensor_number">
                                        {% for sensor in polledSensors %}
                                        <option>{{sensor.address}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-8">

                                <div class="form-group">
                                    <label>Sensor name</label>
                                    <input id="id_Sensor_name" class="form-control" placeholder="Enter sensor name" required type="text" name="Sensor_name" maxlength="100"/>
                                </div>
                                <button value="addSensor" name="submit" class="btn btn-default pull-right" type="submit">Add Sensor</button>
                            </div>
                        </form>
                </div>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Remove Sensor</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <form role="form" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Sensor</label>
                                <select class="form-control" id="id_Sensor_selected" type="number" name="Sensor_selected">
                                    {% for sensor in activeSensors %}
                                    <option>{{sensor.Sensor_number}}: {{sensor.Sensor_name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button value="removeSensor" name="submit" class="btn btn-default pull-right" type="submit">Remove Sensor</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

DjangoProject/SensorPoll/templates/SensorPoll/tables.html
{% extends "base.html" %}

{% block tablesButton %}
    class="active"
{% endblock %}

{% block pageHeader %}
    Tables
    <small>Subheading</small>
{% endblock %}

{% block breadcrumb %}
<li>
    <i class="fa fa-dashboard"></i>  <a href="{% url 'index' %}">Dashboard</a>
</li>
<li class="active">
    <i class="fa fa-table"></i> Tables
</li>
{% endblock %}

{% block row %}
<div class="row">
    <div class="col-lg-6">
        <h2>Bordered with Striped Rows</h2>
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Packet Address</th>
                        <th>Packet Time</th>
                        <th>Packet data</th>

                    </tr>
                </thead>
                <tbody>
                    {% for packet in packets %}
                    <tr>

                        <td> {{packet.address}}</td>
                        <td> {{packet.time_stamp}}</td>
                        <td> {{packet.data}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if packets.has_previous %}
                <a class="btn btn-default" href="?page={{ packets.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ packets.number }} of {{ packets.paginator.num_pages }}.
                </span>

                {% if packets.has_next %}
                <a class="btn btn-default" href="?page={{ packets.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
<!-- /.row -->
{% endblock %}



DjangoProject/SensorPoll/templates/base.html
{% load staticfiles %}
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Sensor E-Perception - The Electronic Sensation</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Morris Charts JavaScript -->
    <script src="{% static 'js/plugins/morris/raphael.min.js' %}"></script>
    <script src="{% static 'js/plugins/morris/morris.min.js' %}"></script>
</head>

<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">Sensor E-Perception</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> User <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <!-- /.navbar-collapse -->
            <!-- /#page-wrapper -->


            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li {% block dashboardButton %}{% endblock %}>
                        <a href="{% url 'index' %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li {% block chartsButton %}{% endblock %}>
                        <a href="{% url 'charts' %}"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
                    </li>
                    <li {% block tablesButton %}{% endblock %}>
                        <a href="{% url 'tables' %}"><i class="fa fa-fw fa-table"></i> Tables</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            {% block pageHeader %}
                            {% endblock %}
                        </h1>
                        <ol class="breadcrumb">
                            {% block breadcrumb %}
                            {% endblock %}
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                {% block row %}
                {% endblock %}
                <!-- /.row -->
                <div class="row">
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
    </div>
    <!-- /#wrapper -->
    {% block chartsData %}
    {% endblock %}
</body>
</html>